apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/spork-madness/multi-platform-test-stage?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: multi-platform-test-stage
    appstudio.openshift.io/component: multi-platform-test-stage
    pipelines.appstudio.openshift.io/type: build
  name: multi-platform-test-stage-on-pull-request
  namespace: arewm-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/arewm-tenant/multi-platform-test-stage/multi-platform-test-stage:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: docker/Dockerfile
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
  pipelineRef:
    name: multi-arch-build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'